### ISSUE TITLE
Provide attribution to Renee French

### ISSUE THREAD

**Issue by eternal-flame-AD** [gotify/logo#1]
As is [indicated](https://blog.golang.org/gopher) on the Go Blog. I think gotify logo should be considered a derived work from the original golang gopher, licenced under CC Attribution 3.0. Therefore we should provide attribution to its author.

**Comment by jmattheis** [comment]
Do you think adding this paragraph to the readme is enough? https://github.com/gotify/logo/commit/2f50c24bed6b4a60c518bd965924d53ad3cd2018

**Comment by eternal-flame-AD** [comment]
Looks good:)
