### ISSUE TITLE
Simplified version

### ISSUE THREAD

**Issue by PanderMusubi** [gotify/logo#3]
Please see https://github.com/gotify/android/issues/196 for request to have also a simplified version of the logo for use as e.g. notification icon.

**Comment by PanderMusubi** [comment]
Work in progress for a monochrome version, filled and outlined. Okay to furhter tune this one and create an PR?

![Screenshot from 2022-06-08 12-06-35](https://user-images.githubusercontent.com/198964/172590677-6e2d9b27-d82e-457f-ab7d-eab9909851c0.png)

**Comment by jmattheis** [comment]
I like the first one, but I'm unsure of how it looks in the notification bar on phones. Maybe there are too many details?

**Comment by PanderMusubi** [comment]
Thanks, the level of detail (line thickness) is the same as in mainstream icons such as that from Synchting. Will let you know once I have tuned it and we can make a test build.

**Comment by PanderMusubi** [comment]
![gotify-logo-monochrome-outline-proposed-3](https://user-images.githubusercontent.com/198964/180733597-bf83593b-de63-4de2-9f79-5928370f9d29.png)

Is this suitable to go forward with?

**Comment by jmattheis** [comment]
I think it has too many details, if you size it down it is pretty difficult to read. Maybe only have the gopher outline with a filled envelope. (without hands & eyes and nose)
![test](https://user-images.githubusercontent.com/14895212/180850160-746dd448-e8ce-49ee-a599-049982bace02.png)

**Comment by PanderMusubi** [comment]
Made it, please review https://github.com/PanderMusubi/logo#notification-logo and let me know. Then I can make a PR.

**Comment by jmattheis** [comment]
Looks good.

**Comment by jmattheis** [comment]
Fixed with #4

**Comment by xmha97** [comment]
> ![gotify-logo-monochrome-outline-proposed-3](https://user-images.githubusercontent.com/198964/180733597-bf83593b-de63-4de2-9f79-5928370f9d29.png)
> 
> Is this suitable to go forward with?

@PanderMusubi 
Please share this icon as SVG format.
I need it for Android monochrome icon.
https://github.com/gotify/android/issues/419

**Comment by PanderMusubi** [comment]
I have searched but no longer have it. You can use e.g. Inkscape to regenerate/trace it.
