### ISSUE TITLE
Small logo as SVG

### ISSUE THREAD

**Issue by desbma** [gotify/logo#5]
Would it possible to provide the "small" logo from https://github.com/gotify/logo/blob/master/gotify-logo-small.png as SVG?

Thanks

**Comment by jmattheis** [comment]
Could you try out https://github.com/gotify/logo/blob/small-svg/gotify-logo-small.svg the view in github looks broken, but when including it in html it looks fine.

**Comment by desbma** [comment]
Thanks! 

Interestingly, Firefox renders it wrong (without horizontal cropping) for example on https://raw.githubusercontent.com/gotify/logo/small-svg/gotify-logo-small.svg, but when downloading the file and opening it with Inkscape, it is correct.

**Comment by jmattheis** [comment]
Fixed with #6

**Comment by desbma** [comment]
Thanks
